r"""Self-exciting multi-armed bandits (Appendix C.1 of the paper).

State :math:`x=(m,b)` with :math:`m\in\{-K_{\max},\dots,-1,1,\dots,K_{\max}\}`
the signed outcome of the last stake and :math:`b\in\{0,\dots,K-1\}` the
last arm played. Action :math:`a=(k,j)` with stake
:math:`k\in\{1,\dots,K_{\max}\}` and arm :math:`j\in\{1,\dots,K\}`.
Self-exciting success probability

.. math::

    \tilde p(x,a) \;=\; p_{j}
        + \kappa\,\operatorname{sign}(m)\,\mathbf 1_{\{b = j-1\}}
        \;\in\; (0,1),

and the next state is generated by
:math:`m'=k\,(2\xi-1)` with :math:`\xi\sim\mathrm{Bernoulli}(\tilde p)`,
:math:`b'=j-1`. The running reward is the signed stake outcome
:math:`f(t,x,a,x')=m'`; terminal reward :math:`g\equiv 0`.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Tuple

import numpy as np


@dataclass
class BanditSpec:
    """Self-exciting bandit parameters (paper default: Appendix C.1)."""
    T:     int   = 5                                       # horizon
    K:     int   = 3                                       # number of arms
    K_max: int   = 2                                       # maximum stake
    kappa: float = 0.2                                     # excitation strength
    p:     Tuple[float, ...] = (0.4, 0.55, 0.35)           # base probabilities


def _states(spec: BanditSpec) -> List[Tuple[int, int]]:
    ms = [m for m in range(-spec.K_max, spec.K_max + 1) if m != 0]
    bs = list(range(spec.K))
    return [(m, b) for m in ms for b in bs]


def _actions(spec: BanditSpec) -> List[Tuple[int, int]]:
    return [(k, j) for k in range(1, spec.K_max + 1) for j in range(1, spec.K + 1)]


def build(spec: BanditSpec):
    """Return ``(P0, reward, terminal, cost, mu0, states, actions)``."""
    states  = _states(spec);  actions = _actions(spec)
    n_x, n_a = len(states), len(actions)
    idx = {s: i for i, s in enumerate(states)}

    P0     = np.zeros((n_x, n_a, n_x))
    reward = np.zeros((n_x, n_a, n_x))
    for i, (m, b) in enumerate(states):
        for j_idx, (k, arm) in enumerate(actions):
            p_tilde = float(np.clip(
                spec.p[arm - 1] + spec.kappa * np.sign(m) * (b == arm - 1),
                0.01, 0.99,
            ))
            up, dn = (+k, arm - 1), (-k, arm - 1)
            P0[i, j_idx, idx[up]] = p_tilde
            P0[i, j_idx, idx[dn]] = 1.0 - p_tilde
            reward[i, j_idx, idx[up]] = +k
            reward[i, j_idx, idx[dn]] = -k

    terminal = np.zeros(n_x)
    pts  = np.array(states, dtype=float)
    cost = np.linalg.norm(pts[:, None, :] - pts[None, :, :], axis=-1)
    mu0  = np.full(n_x, 1.0 / n_x)
    return P0, reward, terminal, cost, mu0, states, actions
